### ISSUE TITLE
No instructions on DB init

### ISSUE THREAD

**Issue by jazing** [geektutor/Leaderboard#226]
With the lack of any instructions on initializing a database, whether to load the root index.php of the application, the index.php with the sub-folder "leaderboard", what to do with the admin folder... There's nothing to go by on using this. C'mon.

Upon first user attempt to "sign-up", the browser shows:

Warning
: mysqli_num_rows() expects parameter 1 to be mysqli_result, bool given in
/Applications/XAMPP/xamppfiles/htdocs/leaderboard/sign_up.php
on line
29

Warning
: mysqli_num_rows() expects parameter 1 to be mysqli_result, bool given in
/Applications/XAMPP/xamppfiles/htdocs/leaderboard/sign_up.php
on line
49

could not enter data: Table 'leader1.user' doesn't exist

...and the PHP processor logs:

PHP Warning:  mysqli_num_rows() expects parameter 1 to be mysqli_result, bool given in /Applications/XAMPP/xamppfiles/htdocs/leaderboard/sign_up.php on line 29
PHP Warning:  mysqli_num_rows() expects parameter 1 to be mysqli_result, bool given in /Applications/XAMPP/xamppfiles/htdocs/leaderboard/sign_up.php on line 49

**Comment by Adebayo27** [comment]
> With the lack of any instructions on initializing a database, whether to load the root index.php of the application, the index.php with the sub-folder "leaderboard", what to do with the admin folder... There's nothing to go by on using this. C'mon.
> 
> Upon first user attempt to "sign-up", the browser shows:
> 
> Warning
> : mysqli_num_rows() expects parameter 1 to be mysqli_result, bool given in
> /Applications/XAMPP/xamppfiles/htdocs/leaderboard/sign_up.php
> on line
> 29
> 
> Warning
> : mysqli_num_rows() expects parameter 1 to be mysqli_result, bool given in
> /Applications/XAMPP/xamppfiles/htdocs/leaderboard/sign_up.php
> on line
> 49
> 
> could not enter data: Table 'leader1.user' doesn't exist
> 
> ...and the PHP processor logs:
> 
> PHP Warning: mysqli_num_rows() expects parameter 1 to be mysqli_result, bool given in /Applications/XAMPP/xamppfiles/htdocs/leaderboard/sign_up.php on line 29
> PHP Warning: mysqli_num_rows() expects parameter 1 to be mysqli_result, bool given in /Applications/XAMPP/xamppfiles/htdocs/leaderboard/sign_up.php on line 49

HOW TO SET UP THIS PROJECT LOCALLY

1. You must have local developer server installed on your machine like XAMPP, WAMP, LAMP

2. Clone the repository to your local machine:

git clone https://github.com/geektutor/Leaderboard.git

3. Move the cloned folder to:

a. for XAMPP: htdocs folder

b. for WAMP: www folder

4. Create a database and name it anything you like. Just make sure you edit the config/connect.php and change the db_name to your database name

5. Run this sql file on your local server in the database you created "mushpgwz_leaderboard.sql"

6. Start your local developer server

7. The project will be available at localhost/Leaderboard

**Comment by jazing** [comment]
I see you've provided a DB schema... but it's populated with 1700+ users and thousands of other table entries. I'm not going to load this SQL into a DB... 

So I emptied all of the tables, and upon submitting the signup form I get:
could not enter data: Field 'participation' doesn't have a default value

No PHP errors...

What is this "Certificate of Participation" stuff?
./admin/cert.php:              <option value="1">Certificate of Participation</option>
./user/certification.php:          $participation = $row['participation'];
./user/certification.php:              <option value="<?php echo $participation; ?>">Certificate of Participation</option>
./certificate.md:* Choose the certificate you want to download (participation or performance)

Is this framework from a class you took? "30DayOfCode 2020"?

**Comment by jazing** [comment]
I realize now that this isn't a leaderboard application.
